### ISSUE TITLE
"Sentry is not fully installed: $sentry not found!"

### ISSUE THREAD

**Issue by m-overlund** [luigifab/openmage-sentry#1]
Are there any dependencies?

Trying to move from Firegento_Logger and I'm getting this error when enabling Sentry:
`Sentry is not fully installed: $sentry not found!`

Used the normal diff (not "more").
Installed via FTP but do not see any composer dependencies.

Exception.log logging:
`isDeveloperMode:off sentry:off`
before the exceptions (unrelated)

```
OpenMage 19.4.23
PHP 8.1
```

**Comment by luigifab** [comment]
Can you check that _app/code/core/Mage/Core/Model/App.php_ is updated? (is `global $sentry;` present?)
And no, there are no dependencies.

**Comment by m-overlund** [comment]
Yes, checked the diff, and it looks good.
![image](https://user-images.githubusercontent.com/504236/232025662-c6583812-6242-4553-a342-37a6920f4646.png)

**Comment by luigifab** [comment]
Have you cleared the cache? I think yes... Perhaps you have a rewrite of this method? Try `exit('this is me');` at the beginning of the method (`Mage_Core_Model_App::_initCurrentStore`)?

**Comment by luigifab** [comment]
Sadly you are right... this does not work.
I'm searching why.

**Comment by luigifab** [comment]
Can you replace in _app/code/community/Luigifab/Sentry/Model/Client.php_ line 35:
`			if ($sentry && is_object($sentry)) {`
by
`			if (!$sentry || !is_object($sentry)) {`

**Comment by m-overlund** [comment]
Sure, will try it out as soon as i have a chance to test it out again :)

**Comment by luigifab** [comment]
Fixed in v2.1.0.
